version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.avse_cm_instance_1.integrations:generateQuotation
  packages:
  - name: EdgeAvse_cm_instance_1
    version: "1.0"
  - name: GP01_OrderManagement-master
    version: "1.0"
- serviceName: gp.order.management.services:generateQuote
  packages:
  - name: EdgeAvse_cm_instance_1
    version: "1.0"
  - name: GP01_OrderManagement-master
    version: "1.0"
- serviceName: gp.order.management.appsim:getCustomerById
  packages:
  - name: GP01_OrderManagement-master
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.json:jsonStringToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: gp.order.management.appsim:getProductById
  packages:
  - name: GP01_OrderManagement-master
    version: "1.0"
- serviceName: pub.string:isNumber
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.math:multiplyFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.math:subtractFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.flow:getLastError
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.flow:clearPipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
packages:
- name: EdgeAvse_cm_instance_1
  gitServerName: selvi_github
  gitUrl: https://github.com/AvudaiSelvi/EdgeAvse_cm_instance_1
  gitUsername: AvudaiSelvi
  gitToken: edge.scaffolding.EdgeAvse_cm_instance_1.selvi_github.gitToken
  gitBranch: main
